import { HomePage } from './home'
import { LoginPage } from './login'
import { RegisterPage } from './registration'
import { ForgotPasswordPage } from './forgot-password'
import { ResetPasswordPage } from './reset-password'
import { ProfilePage } from './profile'
import { IngredientPage } from './ingredient-info'
import { ProfileOrdersPage } from './profile-orders'
import { ProfileAccountPage } from './profile-account'
import { IngredientModal } from './ingredient-modal'
import { NotFound404 } from './not-found'
import { ProfileOrderPage } from './profile-order'
import { FeedOrderPage } from './feed-order'
import { FeedPage } from './feed'
import { ProfileOrderModal } from './profile-order-modal'
import { FeedOrderModal } from './feed-order-modal'

export { HomePage, LoginPage, ProfilePage, IngredientModal, NotFound404, RegisterPage, ForgotPasswordPage, ResetPasswordPage, IngredientPage, ProfileOrdersPage, ProfileAccountPage, ProfileOrderPage, FeedOrderPage, FeedPage, ProfileOrderModal, FeedOrderModal}
